### ISSUE TITLE
Moralis Self hosted server url and App id is necessary in the graph way? 

### ISSUE THREAD

**Issue by dashDebasis123** [PatrickAlphaC/nextjs-nft-marketplace-thegraph-fcc#30]
I am facing difficulty while creating the **self-hosted _Moralis server URL and id_**. Is it necessary to get the Moralis **URL and ID** for the NFT marketplace for the **Graph Method**?

@PatrickAlphaC

**Comment by PatrickAlphaC** [comment]
Skip the moralis section. Sadly, they have discontinued the service. Please go to the section where we use the graph instead.

**Comment by dashDebasis123** [comment]
Hello,
I am using graph, but the code you provided in GitHub uses* Moralis
provider* and in the *event.js* file, they used the server *URL and appId*,
so I wonder whether we still need to use it in the graph method.
Debasis Dash
Mtech(C.S)
SSSIHL

**Comment by dashDebasis123** [comment]
I am using graph, but the code you provided in GitHub uses **Moralis provider** and in the e**vent.js** file, they used the **server URL and appId**, so I wonder whether we still need to use it in the graph method.

**Comment by PatrickAlphaC** [comment]
You should be able to not provide either and it should work fine
